title: Uppsala Workshop
tagline: on Automata, Logic and&nbsp;Verification
date: 23rd-25th Jan&nbsp;2023
loc: in Ångström Laboratory, Uppsala,&nbsp;Sweden
description: Workshop on Automata, Logic and Verification

baseurl: /UUWorkshop/

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
